SELECT 
  CHILD.UNIQUE_ID AS SUCCESSOR,
  PARENT.UNIQUE_ID AS PREDECESSOR,
  START_DATE,
  END_DATE
FROM EDGE 
JOIN NODE CHILD ON CHILD_NODE_ID = CHILD.ID
JOIN NODE PARENT ON PARENT_NODE_ID = PARENT.ID
WHERE HIERARCHY = 'history'