SELECT nat.NODE_ID, nat."KEY", nat."VALUE", nat.START_DATE, nat.END_DATE from NODE_ATTR nat
WHERE  nat.NODE_ID in (
    SELECT N.ID FROM NODE N, NODE_ATTR NA
    WHERE N.ID=NA.NODE_ID AND NA."KEY" = 'iam-johtoryhma'
      AND NA.NODE_ID IN (SELECT NODE_ID FROM NODE_TYPE WHERE
                NODE_TYPE."VALUE" IN ('kandiohjelma', 'maisteriohjelma', 'tohtoriohjelma')
            AND NODE_TYPE.END_DATE IS NULL OR NODE_TYPE.END_DATE > trunc(CURRENT_DATE)
            AND (NODE_TYPE.START_DATE IS NULL OR NODE_TYPE.START_DATE <= trunc(CURRENT_DATE)))
      AND N.ID IN (SELECT CHILD_NODE_ID FROM EDGE WHERE HIERARCHY='toiminnanohjaus')
      AND (N.END_DATE IS NULL OR N.END_DATE > trunc(CURRENT_DATE))
      AND (N.START_DATE IS NULL OR N.START_DATE <= trunc(CURRENT_DATE)))
ORDER BY NODE_ID, "KEY"
