SELECT 
	NODE.START_DATE AS UNIT_START_DATE,
	NODE.UNIQUE_ID AS UNIQUE_ID,
	NAME_FI.VALUE AS NAME_FI,
	NAME_EN.VALUE AS NAME_EN,
	NAME_SV.VALUE AS NAME_SV,
	CODE.VALUE AS CODE,
	TYPE.VALUE AS TYPE,
	PARENT.UNIQUE_ID AS PARENT
FROM NODE
LEFT JOIN EDGE HENKILOSTO ON 
	HENKILOSTO.HIERARCHY = 'henkilosto' AND
	NODE.ID = HENKILOSTO.CHILD_NODE_ID AND
	(HENKILOSTO.START_DATE IS NULL OR HENKILOSTO.START_DATE <= TRUNC(CURRENT_DATE)) AND
	(HENKILOSTO.END_DATE IS NULL OR HENKILOSTO.END_DATE >= TRUNC(CURRENT_DATE))
LEFT JOIN EDGE TUTKIMUSRYHMAT ON
	HENKILOSTO.ID IS NULL AND
	NODE.ID = TUTKIMUSRYHMAT.CHILD_NODE_ID AND
	TUTKIMUSRYHMAT.HIERARCHY = 'tutkimusryhmat' AND
	(TUTKIMUSRYHMAT.START_DATE IS NULL OR TUTKIMUSRYHMAT.START_DATE <= TRUNC(CURRENT_DATE)) AND
	(TUTKIMUSRYHMAT.END_DATE IS NULL OR TUTKIMUSRYHMAT.END_DATE >= TRUNC(CURRENT_DATE))
JOIN NODE_ATTR NAME_FI ON 
	NODE.ID = NAME_FI.NODE_ID AND 
	NAME_FI.KEY = 'name_fi' AND 
	(NAME_FI.START_DATE IS NULL OR NAME_FI.START_DATE <= TRUNC(CURRENT_DATE)) AND 
	(NAME_FI.END_DATE IS NULL OR NAME_FI.END_DATE >= TRUNC(CURRENT_DATE))
JOIN NODE_ATTR NAME_SV ON 
	NODE.ID = NAME_SV.NODE_ID AND 
	NAME_SV.KEY = 'name_sv' AND 
	(NAME_SV.START_DATE IS NULL OR NAME_SV.START_DATE <= TRUNC(CURRENT_DATE)) AND 
	(NAME_SV.END_DATE IS NULL OR NAME_SV.END_DATE >= TRUNC(CURRENT_DATE))
JOIN NODE_ATTR NAME_EN ON 
	NODE.ID = NAME_EN.NODE_ID AND 
	NAME_EN.KEY = 'name_en' AND 
	(NAME_EN.START_DATE IS NULL OR NAME_EN.START_DATE <= TRUNC(CURRENT_DATE)) AND 
	(NAME_EN.END_DATE IS NULL OR NAME_EN.END_DATE >= TRUNC(CURRENT_DATE))
LEFT JOIN NODE_ATTR CODE ON
	HENKILOSTO.ID IS NOT NULL AND
	CODE.NODE_ID = NODE.ID AND
	CODE.KEY = 'hr_lyhenne' AND
	(CODE.START_DATE IS NULL OR CODE.START_DATE <= TRUNC(CURRENT_DATE)) AND
	(CODE.END_DATE IS NULL OR CODE.END_DATE >= TRUNC(CURRENT_DATE))
JOIN HIERARCHY_FILTER TYPE_HIERARCHY_FILTER ON
	(TYPE_HIERARCHY_FILTER.HIERARCHY = HENKILOSTO.HIERARCHY OR TYPE_HIERARCHY_FILTER.HIERARCHY = TUTKIMUSRYHMAT.HIERARCHY) AND
	TYPE_HIERARCHY_FILTER.KEY = 'type' AND
	(TYPE_HIERARCHY_FILTER.START_DATE IS NULL OR TYPE_HIERARCHY_FILTER.START_DATE <= TRUNC(CURRENT_DATE)) AND
	(TYPE_HIERARCHY_FILTER.END_DATE IS NULL OR TYPE_HIERARCHY_FILTER.END_DATE >= TRUNC(CURRENT_DATE))
JOIN NODE_ATTR TYPE ON
	TYPE.NODE_ID = NODE.ID AND
	TYPE.KEY = TYPE_HIERARCHY_FILTER.KEY AND
	TYPE.VALUE = TYPE_HIERARCHY_FILTER.VALUE AND
	(TYPE.START_DATE IS NULL OR TYPE.START_DATE <= TRUNC(CURRENT_DATE)) AND
	(TYPE.END_DATE IS NULL OR TYPE.END_DATE >= TRUNC(CURRENT_DATE))
LEFT JOIN NODE PARENT ON
	(HENKILOSTO.PARENT_NODE_ID IS NOT NULL AND HENKILOSTO.PARENT_NODE_ID = PARENT.ID) OR
	(TUTKIMUSRYHMAT.PARENT_NODE_ID IS NOT NULL AND TUTKIMUSRYHMAT.PARENT_NODE_ID = PARENT.ID)
WHERE
	HENKILOSTO.ID IS NOT NULL OR 
	TUTKIMUSRYHMAT.ID IS NOT NULL
