INSERT INTO NODE_ATTR (ID, NODE_ID, KEY, VALUE, START_DATE, END_DATE)
VALUES (:id, :node_id, :key, :value, FROM_TZ(TO_TIMESTAMP(:start_date, 'DD.MM.YYYY'),'0:00'), FROM_TZ(TO_TIMESTAMP(:end_date, 'DD.MM.YYYY'),'0:00'))
