WITH ROOT (NAME, PARENT_NODE_ID, CHILD_NODE_ID, LEVEL_ONE) AS (
  SELECT 
    NODE.NAME,
    EDGE.PARENT_NODE_ID PARENT_NODE_ID,
    EDGE.CHILD_NODE_ID CHILD_NODE_ID,
    EDGE.CHILD_NODE_ID LEVEL_ONE
  FROM NODE 
    JOIN EDGE ON NODE.ID = EDGE.CHILD_NODE_ID 
      AND EDGE.HIERARCHY = 'henkilosto'
      AND (EDGE.START_DATE IS NULL OR EDGE.START_DATE <= TRUNC(CURRENT_DATE))
      AND (EDGE.END_DATE IS NULL OR EDGE.END_DATE >= TRUNC(CURRENT_DATE))
    LEFT JOIN NODE_ATTR HENKILOSTOYKSIKKO
      ON NODE.ID = HENKILOSTOYKSIKKO.NODE_ID
      AND HENKILOSTOYKSIKKO.KEY = 'type'
      AND HENKILOSTOYKSIKKO.VALUE = 'henkilostoyksikko'
      AND (HENKILOSTOYKSIKKO.START_DATE IS NULL OR HENKILOSTOYKSIKKO.START_DATE <= TRUNC(CURRENT_DATE))
      AND (HENKILOSTOYKSIKKO.END_DATE IS NULL OR HENKILOSTOYKSIKKO.END_DATE >= TRUNC(CURRENT_DATE))
    LEFT JOIN NODE_ATTR KANSIO
      ON NODE.ID = KANSIO.NODE_ID
      AND KANSIO.KEY = 'type'
      AND KANSIO.VALUE = 'kansio'
      AND (KANSIO.START_DATE IS NULL OR KANSIO.START_DATE <= TRUNC(CURRENT_DATE))
      AND (KANSIO.END_DATE IS NULL OR KANSIO.END_DATE >= TRUNC(CURRENT_DATE))
    WHERE
      HENKILOSTOYKSIKKO.ID IS NULL 
      AND KANSIO.ID IS NULL
      AND (NODE.START_DATE IS NULL OR NODE.START_DATE <= TRUNC(CURRENT_DATE))
      AND (NODE.END_DATE IS NULL OR NODE.END_DATE >= TRUNC(CURRENT_DATE))
    UNION ALL
    SELECT
      NODE.NAME,
      EDGE.PARENT_NODE_ID,
      EDGE.CHILD_NODE_ID,
      ROOT.LEVEL_ONE
    FROM ROOT
      JOIN EDGE ON ROOT.CHILD_NODE_ID = EDGE.PARENT_NODE_ID AND EDGE.HIERARCHY = 'henkilosto'
          AND (EDGE.START_DATE IS NULL OR EDGE.START_DATE <= TRUNC(CURRENT_DATE))
          AND (EDGE.END_DATE IS NULL OR EDGE.END_DATE >= TRUNC(CURRENT_DATE))
      JOIN NODE ON NODE.ID = EDGE.CHILD_NODE_ID
        AND (NODE.START_DATE IS NULL OR NODE.START_DATE <= TRUNC(CURRENT_DATE))
        AND (NODE.END_DATE IS NULL OR NODE.END_DATE >= TRUNC(CURRENT_DATE))
      JOIN NODE_ATTR ON NODE.ID = NODE_ATTR.NODE_ID
        AND NODE_ATTR.KEY = 'type'
        AND NODE_ATTR.VALUE IN ('henkilostoyksikko', 'kansio')
        AND (NODE_ATTR.START_DATE IS NULL OR NODE_ATTR.START_DATE <= TRUNC(CURRENT_DATE))
        AND (NODE_ATTR.END_DATE IS NULL OR NODE_ATTR.END_DATE >= TRUNC(CURRENT_DATE))
) SELECT 
    SUB_UNIT_CODE.VALUE AS SUB_UNIT_CODE, 
    LEVEL_ONE_UNIT_CODE.VALUE AS UNIT_CODE,
    LEVEL_ONE_NAME.VALUE AS UNIT_NAME_FI
  FROM ROOT 
  JOIN NODE_ATTR SUB_UNIT_CODE
    ON ROOT.CHILD_NODE_ID = SUB_UNIT_CODE.NODE_ID
    AND SUB_UNIT_CODE.KEY = 'hr_lyhenne'
    AND (SUB_UNIT_CODE.START_DATE IS NULL OR SUB_UNIT_CODE.START_DATE <= TRUNC(CURRENT_DATE))
    AND (SUB_UNIT_CODE.END_DATE IS NULL OR SUB_UNIT_CODE.END_DATE >= TRUNC(CURRENT_DATE))
  JOIN NODE_ATTR LEVEL_ONE_UNIT_CODE 
    ON ROOT.LEVEL_ONE = LEVEL_ONE_UNIT_CODE.NODE_ID
    AND LEVEL_ONE_UNIT_CODE.KEY = 'hr_lyhenne'
    AND (LEVEL_ONE_UNIT_CODE.START_DATE IS NULL OR LEVEL_ONE_UNIT_CODE.START_DATE <= TRUNC(CURRENT_DATE))
    AND (LEVEL_ONE_UNIT_CODE.END_DATE IS NULL OR LEVEL_ONE_UNIT_CODE.END_DATE >= TRUNC(CURRENT_DATE))
  JOIN NODE_ATTR LEVEL_ONE_NAME
    ON ROOT.LEVEL_ONE = LEVEL_ONE_NAME.NODE_ID
    AND LEVEL_ONE_NAME.KEY = 'name_fi'
    AND (LEVEL_ONE_NAME.START_DATE IS NULL OR LEVEL_ONE_NAME.START_DATE <= TRUNC(CURRENT_DATE))
    AND (LEVEL_ONE_NAME.END_DATE IS NULL OR LEVEL_ONE_NAME.END_DATE >= TRUNC(CURRENT_DATE))
  LEFT JOIN NODE_ATTR KANSIO ON KANSIO.NODE_ID = ROOT.CHILD_NODE_ID 
    AND KANSIO.KEY = 'type' 
    AND KANSIO.VALUE = 'kansio'
    AND (KANSIO.START_DATE IS NULL OR KANSIO.START_DATE <= TRUNC(CURRENT_DATE))
    AND (KANSIO.END_DATE IS NULL OR KANSIO.END_DATE >= TRUNC(CURRENT_DATE))
  WHERE KANSIO.ID IS NULL
  ORDER BY UNIT_CODE, SUB_UNIT_CODE