SELECT DISTINCT
	NODE.UNIQUE_ID,
	NAME_FI.VALUE AS NAME_FI,
	NAME_EN.VALUE AS NAME_EN,
	NAME_SV.VALUE AS NAME_SV
FROM EDGE 
	JOIN NODE ON EDGE.CHILD_NODE_ID = NODE.ID
	JOIN HIERARCHY_PUBLICITY PUBLICITY 
		ON EDGE.HIERARCHY = PUBLICITY.HIERARCHY AND PUBLICITY.PUBLICITY = 1
	JOIN NODE_ATTR NAME_FI ON NAME_FI.NODE_ID = NODE.ID 
		AND NAME_FI.KEY = 'name_fi'
	  AND (NAME_FI.START_DATE IS NULL OR NAME_FI.START_DATE <= TRUNC(CURRENT_DATE))
	  AND (NAME_FI.END_DATE IS NULL OR NAME_FI.END_DATE >= TRUNC(CURRENT_DATE))
	JOIN NODE_ATTR NAME_EN ON NAME_EN.NODE_ID = NODE.ID
	  AND NAME_EN.KEY = 'name_en'
		AND (NAME_EN.START_DATE IS NULL OR NAME_EN.START_DATE <= TRUNC(CURRENT_DATE))
		AND (NAME_EN.END_DATE IS NULL OR NAME_EN.END_DATE >= TRUNC(CURRENT_DATE))
	JOIN NODE_ATTR NAME_SV ON NAME_SV.NODE_ID = NODE.ID
		AND NAME_SV.KEY = 'name_sv'
		AND (NAME_SV.START_DATE IS NULL OR NAME_EN.START_DATE <= TRUNC(CURRENT_DATE))
		AND (NAME_SV.END_DATE IS NULL OR NAME_SV.END_DATE >= TRUNC(CURRENT_DATE))
	WHERE (EDGE.START_DATE IS NULL OR EDGE.START_DATE <= TRUNC(CURRENT_DATE))
	  AND (EDGE.END_DATE IS NULL OR EDGE.END_DATE >= TRUNC(CURRENT_DATE))
	  AND EDGE.HIERARCHY IN (:hierarchies)
