SELECT SUCCESSOR_RELATION.SUCCESSOR_ID AS ID, NODE.NAME, NODE.START_DATE, NODE.END_DATE, SUCCESSOR_RELATION.START_DATE AS EDGE_START_DATE,
                SUCCESSOR_RELATION.END_DATE AS EDGE_END_DATE, NODE.UNIQUE_ID
                FROM SUCCESSOR_RELATION
                INNER JOIN NODE
                ON SUCCESSOR_RELATION.SUCCESSOR_ID = NODE.ID
                WHERE NODE_ID = :endId
