SELECT 
	S.SUCCESSOR_ID AS ID,
	SUCCESSOR.UNIQUE_ID,
	SUCCESSOR.START_DATE,
	SUCCESSOR.END_DATE,
	S.ID AS EDGE_ID,
	S.START_DATE AS EDGE_START_DATE,
	S.END_DATE AS EDGE_END_DATE,
	COALESCE(CURR.NAME, FUTURE.NAME, PAST.NAME, SUCCESSOR.NAME) FULL_NAME,
	COALESCE(CURR.LANGUAGE, FUTURE.LANGUAGE, PAST.LANGUAGE) AS LANGUAGE
FROM SUCCESSOR_RELATION S
	JOIN NODE SUCCESSOR ON S.SUCCESSOR_ID = SUCCESSOR.ID
	LEFT JOIN FULL_NAME PAST ON SUCCESSOR.ID = PAST.NODE_ID
		AND SUCCESSOR.END_DATE < TRUNC(CURRENT_DATE)
		AND (PAST.START_DATE IS NULL OR PAST.START_DATE < SUCCESSOR.END_DATE)
		AND (PAST.END_DATE = SUCCESSOR.END_DATE)
	LEFT JOIN FULL_NAME CURR ON SUCCESSOR.ID = CURR.NODE_ID
		AND (SUCCESSOR.START_DATE IS NULL OR SUCCESSOR.START_DATE < TRUNC(CURRENT_DATE))
		AND (SUCCESSOR.END_DATE IS NULL OR SUCCESSOR.END_DATE >= TRUNC(CURRENT_DATE))
		AND (CURR.START_DATE IS NULL OR CURR.START_DATE < TRUNC(CURRENT_DATE))
		AND (CURR.END_DATE IS NULL OR CURR.END_DATE >= TRUNC(CURRENT_DATE))
	LEFT JOIN FULL_NAME FUTURE ON SUCCESSOR.ID = CURR.NODE_ID
		AND (SUCCESSOR.START_DATE > TRUNC(CURRENT_DATE))
		AND (FUTURE.START_DATE <= SUCCESSOR.START_DATE)
		AND (FUTURE.END_DATE IS NULL OR FUTURE.END_DATE = SUCCESSOR.START_DATE)
	WHERE S.NODE_ID = :nodeId