WITH NODES AS (SELECT DISTINCT CHILD_NODE_ID, PARENT_NODE_ID, LEVEL FROM EDGE WHERE
    (END_DATE IS NULL OR END_DATE > trunc(:date))
        AND (START_DATE IS NULL OR START_DATE <= trunc(:date))
            AND HIERARCHY = :hierarchy
               START WITH PARENT_NODE_ID = 'a1'
               CONNECT BY NOCYCLE PRIOR CHILD_NODE_ID = PARENT_NODE_ID and HIERARCHY = :hierarchy
                      AND (END_DATE IS NULL OR END_DATE > trunc(:date))
                      AND (START_DATE IS NULL OR START_DATE <= trunc(:date)) ORDER BY LEVEL)
SELECT NC.*,N.UNIQUE_ID, ATTR.VALUE AS CODE, N_FI.NAME NAME_FI,N_EN.NAME NAME_EN,N_SV.NAME NAME_SV FROM NODES NC, NODE N, NODE_ATTR ATTR, FULL_NAME N_FI, FULL_NAME N_EN, FULL_NAME N_SV
WHERE NC.CHILD_NODE_ID = N_FI.NODE_ID and NC.CHILD_NODE_ID = N.ID AND N.ID = ATTR.NODE_ID AND NC.CHILD_NODE_ID = ATTR.NODE_ID
  AND (N_FI.END_DATE IS NULL OR N_FI.END_DATE > trunc(:date))
  AND (N_FI.START_DATE IS NULL OR N_FI.START_DATE <= trunc(:date))
  AND N_FI.LANGUAGE='fi'
  AND NC.CHILD_NODE_ID = N_EN.NODE_ID and NC.CHILD_NODE_ID = N.ID AND N.ID = ATTR.NODE_ID AND NC.CHILD_NODE_ID = ATTR.NODE_ID
  AND (N_EN.END_DATE IS NULL OR N_EN.END_DATE > trunc(:date))
  AND (N_EN.START_DATE IS NULL OR N_EN.START_DATE <= trunc(:date))
  AND N_EN.LANGUAGE='en'
  AND NC.CHILD_NODE_ID = N_SV.NODE_ID and NC.CHILD_NODE_ID = N.ID AND N.ID = ATTR.NODE_ID AND NC.CHILD_NODE_ID = ATTR.NODE_ID
  AND (N_SV.END_DATE IS NULL OR N_SV.END_DATE > trunc(:date))
  AND (N_SV.START_DATE IS NULL OR N_SV.START_DATE <= trunc(:date))
  AND N_SV.LANGUAGE='sv'
  AND ATTR.KEY = 'talous_tunnus'
  AND (ATTR.END_DATE IS NULL OR ATTR.END_DATE > trunc(:date))
  AND (ATTR.START_DATE IS NULL OR ATTR.START_DATE <= trunc(:date))
UNION
SELECT N.ID ,NULL, 0, N.UNIQUE_ID, 'HY', N_FI.NAME CHILD_NAME_FI,N_EN.NAME CHILD_NODE_EN,N_SV.NAME CHILD_NODE_SV from NODE N, NODE_ATTR ATTR, FULL_NAME N_FI, FULL_NAME N_EN, FULL_NAME N_SV
WHERE 'a1' = N_FI.NODE_ID and 'a1' = N.ID and N.ID = ATTR.NODE_ID
  AND (N_FI.END_DATE IS NULL OR N_FI.END_DATE > trunc(:date))
  AND (N_FI.START_DATE IS NULL OR N_FI.START_DATE <= trunc(:date))
  AND N_FI.LANGUAGE='fi'
  AND 'a1' = N_EN.NODE_ID AND 'a1' = N.ID AND N.ID = ATTR.NODE_ID
  AND (N_EN.END_DATE IS NULL OR N_EN.END_DATE > trunc(:date))
  AND (N_EN.START_DATE IS NULL OR N_EN.START_DATE <= trunc(:date))
  AND N_EN.LANGUAGE='en'
  AND 'a1' = N_SV.NODE_ID and 'a1' = N.ID and N.ID = ATTR.NODE_ID
  AND (N_SV.END_DATE IS NULL OR N_SV.END_DATE > trunc(:date))
  AND (N_SV.START_DATE IS NULL OR N_SV.START_DATE <= trunc(:date))
  AND N_SV.LANGUAGE='sv'
